### ISSUE TITLE
Latest update incorrectly updated a bunch of skill levels/weapons for unowned characters

### ISSUE THREAD

**Issue by zedekblue** [xanthics/genshin_grind_planner#6]
Page has been open all day. Refreshed to check if Eula had been added, and she was, but somehow already had copied all the levels and stats of hu tao, directly below her.
Looking through the list, it looks like quite a few characters were incorrectly updated/changed as well. Seems like it was exclusively characters I didn't own/unchecked/had only at lvl 1 talents/lvl 1/lvl 80+ ascention goal (my default so I can hoard materials)
Using latest version of firefox. I wish I could provide the site cookies as proof but I went and fixed everything I noticed before thinking of opening a bug report.
Hopefully a one-time issue?

**Comment by zedekblue** [comment]
Should also note that somehow these broken characters had a checked box, but showed up as unchecked and greyed out.

Seems my inventory also got messed with, much with the same issue, numbers were changed, seemingly copied from the materials list below, but it didn't update the actual script since they still show as missing.
![Capture](https://user-images.githubusercontent.com/17040113/118996073-dd7fff80-b944-11eb-9642-3a0415e563af.PNG)

**Comment by xanthics** [comment]
Investigating.  My personal setup and test setups didn't have issue so I'll need to figure out how to replicate.  Currently looking through everything that was committed this morning.

**Comment by xanthics** [comment]
As a note I test on firefox and chrome.  The commit looks clean https://github.com/xanthics/genshin_grind_planner/commit/10b9383e4e1ffd3ee57a6772febe5b17cddb45cd which makes me wonder if it is an issue with local storage.  As I am storing a lot of key, I may need to change how data is stored so looking in to that some more.  As I can't repeat the issue you had, and the code looks correct, I'm going to leave this issue open for now but I don't see anything to fix (yet?).

**Comment by xanthics** [comment]
Please reopen, or make a new issue if you experience this bug again.  I recently added a new character without issue for myself.
