### ISSUE TITLE
Missing Dodoco Tales

### ISSUE THREAD

**Issue by rikai** [xanthics/genshin_grind_planner#7]
The planner is missing the latest event weapon [Dodoco Tales](https://genshin-impact.fandom.com/wiki/Dodoco_Tales). Just figured I'd mention it since it's a top-tier weapon for Yanfei. :)

**Comment by xanthics** [comment]
Thank you for the notice, I've been taking a break from Genshin.  Added with c68b61bb98526dcb8cad36a9aef609388dcb3fd5
